name: CI
on:
  pull_request:
    types: [opened, reopened]
  push:
    branches: ["**"]
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-*"

jobs:
  images:
    name: Build container images
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: docker://quay.io/cilium/image-maker:e8f1fa622dfad4250723d55bc6a3dd6d1f0f13cd
        env:
          ANY_REGISTRY_DISABLE: true
          DOCKER_HUB_PUBLIC_ACCESS_ONLY: true
          GHCR_USERNAME: $GITHUB_ACTOR
          GHCR_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        with:
          entrypoint: make
          args: images.hubble-otel images.otelcol PUSH=true
